apiVersion: v1
kind: Pod
metadata:
  name: memory-ctr
  labels:
    name: memory-ctr
spec:
  containers:
  - name: memory-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "180Mi"
        cpu: "50m"
      requests:
        memory: "64Mi"
    # ports:
    #   - containerPort: <Port>
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "15M", "--vm-hang", "1"]
