apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeexpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeexpress-deployment
  template:
    metadata:
      labels:
        app: nodeexpress-deployment
    spec:
      containers:
      - name: nodeexpress
        image: dwinurhadi17/express_app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
      nodeSelector:
        hardware: high-spec