apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeexpress-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeexpress-pod
  template:
    metadata:
      labels:
        app: nodeexpress-pod
    spec:
      containers:
      - name: nodeexpress
        image: dwinurhadi17/express_app:latest
        resources:
          limits:
            memory: "54Mi"
            cpu: "25m"
        ports:
        - name: nodejs-port
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        