apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeexpress-deployment
spec:
  selector:
    matchLabels:
      app: nodeexpress
  template:
    metadata:
      labels:
        app: nodeexpress
    spec:
      containers:
      - name: nodeexpress
        image: dwinurhadi17/express_app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
