apiVersion: v1
kind: Pod
metadata:
  name: nodeexpress-pod
  labels:
    app: nodeexpress-pod
spec:
  containers:
  - name: nodeexpress
    image: dwinurhadi17/express_app:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
      - name: nodejs-port
        containerPort: 3000
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name:  db-secret
            key: username
      - name: SECRECT_PASSWORD
        valueFrom:
          secretKeyRef:
            name:  db-secret
            key: password
          
    
