apiVersion: v1
kind: Pod
metadata:
  name: nodeexpress-pod
  labels:
    name: nodeexpress-pod
spec:
  containers:
  - name: nodeexpress
    image: dwinurhadi17/express_app:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: nodejs-port
        containerPort: 3000
