apiVersion: v1
kind: Pod
metadata:
  name: nodeexpress
  labels:
    app: nodeexpress
spec:
  containers:
  - name: nodeexpress
    image: dwinurhadi17/express_app:latest
    ports:
    - containerPort: 3000
  