kind: Deployment
apiVersion: apps/v1
metadata:
  name: lifecycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lifecycle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lifecycle
    spec:
      initContainers:
      - name:     init
        image:    busybox
        command:  ['sh', '-c', 'sleep 10']        
      containers:        
      - name: lifecycle-container
        image: busybox
        resources:
          limits:
            memory: "512M"
            cpu: "4"
          requests:
            memory: 256Mi
            cpu: "0.2"            
        command: ['sh','-c', 'echo $(date +%s): Running >> /timing && echo "The app is running !" && /bin/sleep 120']
        readinessProbe:
          exec:
            command: ['sh','-c', 'echo $(date +%s): readinessProbe >> /timing']
          initialDelaySeconds: 60
        livenessProbe:
          exec:
            command: ['sh','-c', 'echo $(date +%s): livenessProbe >> /timing']
          initialDelaySeconds: 60
          timeoutSeconds: 10
        lifecycle:
          postStart:
            exec:
              command: ['sh','-c', 'echo $(date +%s): postStart >> /timing && sleep 10 && echo $(date + %s): end postStart >> /timing']
          preStop:
            exec:
              command: ['sh','-c', 'echo $(date +%s): preStop >> /timing && sleep 10']

