apiVersion: v1
kind: ReplicationController
metadata:
  name: nodeexpress-replication
spec:
  replicas: 2
  selector:
    app: nodeexpress-pod
  template:
    metadata:
      labels:
        app: nodeexpress-pod
    spec:
      containers:
      - name: nodeexpress
        image: dwinurhadi17/express_app:latest
        ports:
        - containerPort: 3000
  