apiVersion: v1
kind: ReplicationController
metadata:
  name: nodeexpress
spec:
  replicas: 1
  selector:
    app: nodeexpress
  template:
    metadata:
      labels:
        app: nodeexpress
    spec:
      containers:
      - name: nodeexpress
        image: dwinurhadi17/express_app:latest
        ports:
        - containerPort: 3000
  