apiVersion: v1
kind: Service
metadata:
  name: nodeexpress-service
spec:
  selector:
    app: nodeexpress
  ports:
  - port: 3000
    nodePort: 31001
    targetPort: nodejs-port
    protocol: TCP
  type: NodePort
