apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistence-volume
  labels:
    type: locals
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wordpress"

